// First Commit: 2013-11-05
//
// Authors:
// - Brian Craig
// - Nick Collier
// - Ralph Muehleisen
//
// Summary:
// This file provides the definitions for the `Structure` class constructor
// and destructor. Explicitly defining these in the source file ensures that
// the symbols for this exported class are correctly generated by the linker,
// which is important for shared library compatibility.

#include "Structure.hpp"

namespace openstudio::isomodel {

// Explicitly default constructor and destructor in the source file
// to ensure linker symbols are generated for the exported class.
Structure::Structure() = default;
Structure::~Structure() = default;

} // namespace openstudio::isomodel
